<?php

namespace App\Providers\Faker;

use Faker\Provider\Base;

class FilmTitleProvider extends Base
{
    protected static $filmTitles = [
        'The Shawshank Redemption',
        'The Godfather',
        'Pulp Fiction',
        'The Dark Knight',
        'Inception',
        'Fight Club',
        'Forrest Gump',
        'The Matrix',
        'Good Will Hunting',
        'Interstellar',
        'The Lord of the Rings: The Return of the King',
        'Schindler\'s List',
        'The Silence of the Lambs',
        'Gladiator',
        'The Departed',
        'The Social Network',
        'The Usual Suspects',
        'Se7en',
        'The Prestige',
        'Django Unchained',
        'The Lion King',
        'Titanic',
        'Jurassic Park',
        'Star Wars: Episode IV - A New Hope',
        'Back to the Future',
        'The Avengers',
        'Spider',
        'The Terminator',
        'Avatar',
        'The Wizard of Oz',
        'Casablanca',
        'Gone with the Wind',
        'The Great Gatsby',
        'The Big Lebowski',
        'Fight Club',
        'The Breakfast Club',
        'The Truman Show',
        'Eternal Sunshine of the Spotless Mind',
        'The Green Mile',
        'Saving Private Ryan',
        'The Pianist',
        'A Beautiful Mind',
        'The Intouchables',
        'Amélie',
        'La La Land',
        'Parasite',
        'Whiplash',
        'Moonlight',
        'The Shape of Water',
        '1917',
        'Once Upon a Time in Hollywood',
        'Knives Out',
        'Jojo Rabbit',
        'The Irishman',
        'Marriage Story',
        'The Grand Budapest Hotel',
        'The Hateful Eight',
        'Mad Max: Fury Road',
        'Blade Runner 2049',
        'Spider-Man: Into the Spider-Verse',
        'Black Panther',
        'Wonder',
        'Coco',
        'Inside Out',
        'Zootopia',
        'Toy Story 3',
        'Finding Nemo',
        'Up',
        'WALL-E',
        'The Incredibles',
        'Ratatouille',
        'Monsters, Inc.',
        'Shrek',
        'Kung Fu Panda',
    ];

    public function filmTitle()
    {
        return $this->generator->unique()->randomElement(self::$filmTitles);
    }
}
